### DISCUSSION TITLE
How to add MySQL and PostgreSQL to Docker

### DISCUSSION THREAD

**Discussion by yogeshvachhani** [lowcoder-org/lowcoder#160] [Q&A] [answered]
I checked the Docker configuration/docker-compose file in that only MongoDB is getting installed. 

I want to install two other databases.

1. MySQL 
2. PostgreSQL

How to modify the file and configure these two RDBMS?

Regards,

Yogesh

**Comment by FalkWolsky** [comment, marked as answer]
Typically you would only add this as new sections to the docker-compose file.

For MySQL:

```
services:
  db:
    image: mysql:5.7 #or any other version
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
```

And Postgres:

```
services:
  db:
    image: postgres:14.1-alpine #or any other version
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
```

These are just examples.
