### ISSUE TITLE
[Bug]: N8n/API Service is busy, please try again later.

### ISSUE THREAD

**Issue by gboxxx** [lowcoder-org/lowcoder#1413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to access the API using API key, but getting response `5000 - Oops! Service is busy, please try again later.` This all started from trying to connect to Lowcoder from N8n using the community node, but cannot see any apps in the list, all the while receiving a successfully connected authentication test.  

![CleanShot 2024-12-25 at 07 01 16@2x](https://github.com/user-attachments/assets/3f3923ed-4d20-496f-8534-1421baf96d69)

![CleanShot 2024-12-25 at 07 00 07@2x](https://github.com/user-attachments/assets/480afb17-3f48-4302-94c4-ffde0ef03311)

I've made sure I have a published app in my workspace, but can't seem to get the list to display. Also tried to manually access an app via ID, but N8N doesn't do anything. 

Please advise!

### Expected Behavior

Connect to API using Bearer token and n8n node using email/password. 

### Steps to reproduce

1. Set up n8n community node and add authentication. 
2. Try to select an app from list. 

1. Connect to API at https://my-domain.com/api/users/me using Bearer token

### Environment

Single-Stack docker, latest version hosted locally with a Nginx Proxy Manager/Cloudflare domain setup. 

Docker-Compose.yml
```
version: "3"
services:

  ##
  ## Start Lowcoder (all-in-one)
  ##
  lowcoder-api-service:
    image: lowcoderorg/lowcoder-ce:latest
    container_name: lowcoder
    ports:
      - "3592:3000"
      - "3443:3443"
    environment:
      # Public base url
      LOWCODER_PUBLIC_URL: "https://lowcode.my-domain.com"
      # enable services
      LOWCODER_REDIS_ENABLED: "true"
      LOWCODER_MONGODB_ENABLED: "true"
      LOWCODER_MONGODB_EXPOSED: "false"
      LOWCODER_API_SERVICE_ENABLED: "true"
      LOWCODER_NODE_SERVICE_ENABLED: "true"
      LOWCODER_FRONTEND_ENABLED: "true"
      # generic parameters
      LOWCODER_PUID: "1000"
      LOWCODER_PGID: "1000"
      # api-service parameters
      LOWCODER_MAX_ORGS_PER_USER: 100
      LOWCODER_MAX_MEMBERS_PER_ORG: 1000
      LOWCODER_MAX_GROUPS_PER_ORG: 100
      LOWCODER_MAX_APPS_PER_ORG: 1000
      LOWCODER_MAX_DEVELOPERS: 50
      LOWCODER_MONGODB_URL: "mongodb://localhost:27017/lowcoder?authSource=admin"
      LOWCODER_REDIS_URL: "redis://localhost:6379"
      LOWCODER_EMAIL_SIGNUP_ENABLED: "true"
      LOWCODER_EMAIL_AUTH_ENABLED: "true"
      LOWCODER_CREATE_WORKSPACE_ON_SIGNUP: "true"
      LOWCODER_DB_ENCRYPTION_PASSWORD: "my-encryption-password"
      LOWCODER_DB_ENCRYPTION_SALT: "my-encryption-salt"
      LOWCODER_CORS_DOMAINS: "*"
      LOWCODER_API_KEY_SECRET: "my-api-key-secret"
      # api and node service parameters
      LOWCODER_PLUGINS_DIR: "../plugins"
      LOWCODER_API_RATE_LIMIT: 50
      LOWCODER_API_SERVICE_URL: "http://localhost:8080"
      LOWCODER_NODE_SERVICE_URL: "http://localhost:6060"
      # frontend parameters
      LOWCODER_MAX_REQUEST_SIZE: 20m
      LOWCODER_MAX_QUERY_TIMEOUT: 120
      LOWCODER_WORKSPACE_MODE: SAAS
      LOWCODER_MARKETPLACE_PRIVATE_MODE: "true"
      # Lowcoder notification emails setup
      LOWCODER_ADMIN_SMTP_HOST: "smtp.example.com"
      LOWCODER_ADMIN_SMTP_PORT: 587
      LOWCODER_ADMIN_SMTP_USERNAME: "my-email@example.com"
      LOWCODER_ADMIN_SMTP_PASSWORD: "my-smtp-password"
      LOWCODER_ADMIN_SMTP_AUTH: "true"
      LOWCODER_ADMIN_SMTP_SSL_ENABLED: "false"
      LOWCODER_ADMIN_SMTP_STARTTLS_ENABLED: "true"
      LOWCODER_ADMIN_SMTP_STARTTLS_REQUIRED: "true"
      LOWCODER_EMAIL_NOTIFICATIONS_SENDER: "my-email@example.com"
      LOWCODER_SUPERUSER_USERNAME: "admin@example.com"
      LOWCODER_SUPERUSER_PASSWORD: "my-password"
    volumes:
      - ./lowcoder-stacks:/lowcoder-stacks
      - ./lowcoder-stacks/assets:/lowcoder/assets
    restart: unless-stopped
  ```
