### ISSUE TITLE
[Feat]: allow setting LOWCODER_ADMIN_SMTP_* environment variables in helm chart

### ISSUE THREAD

**Issue by q-gandhart** [lowcoder-org/lowcoder#1691]
I couldn't find a way to set the `LOWCODER_ADMIN_SMTP_*` environment variables in the helm chart values.yaml file. Since, `LOWCODER_ADMIN_SMTP_PASSWORD` is a sensitive secret, we should have a secret reference in the values.yaml file to set this value.

something along these lines

```
global:
  config:
    ...
    admin_smtp_password_secret_ref: foo
```
