### ISSUE TITLE
[Bug]: /api/plugins/enterprise/branding 404 NOT_FOUND

### ISSUE THREAD

**Issue by liborburda** [lowcoder-org/lowcoder#1762]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When Lowcoder is deployed using Helm chart, 404 NOT_FOUND error appears in logs of `api-service` Pod when application is accessed.

### Expected Behavior

No error appears in logs.

### Steps to reproduce

1) Create `values-test.yaml` file with following content:
```
global:
  config:
    workspaceMode: ENTERPRISE

redis:
  networkPolicy:
    enabled: false

mongodb:
  networkPolicy:
    enabled: false
  architecture: standalone
  service:
    nameOverride: "lowcoder-test-mongodb"

ingress:
  enabled: true
  className: nginx-private
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: lowcoder-test.poc.<my-domain>.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: lowcoder-test-ingress-tls
      hosts:
        - lowcoder-test.poc.<my-domain>.com
```
2) Deploy Application using Helm chart with following command:
```
cd deploy/helm
helm upgrade --install -n poc lowcoder-test . -f values-test.yaml
```
3) Access Lowcoder in browser at URL `https://lowcoder-test.poc.<my-domain>.com`

4) Check logs of `lowcoder-test-api-service` Pod (see the full logfile `lowcoder-error.log` attached)

[lowcoder-error.log](https://github.com/user-attachments/files/20669600/lowcoder-error.log)

### Environment

```
$ kubectl version
Client Version: v1.33.1
Kustomize Version: v5.6.0
Server Version: v1.30.6+rke2r1
```
```
$ helm version
version.BuildInfo{Version:"v3.17.3", GitCommit:"e4da49785aa6e6ee2b86efd5dd9e43400318262b", GitTreeState:"clean", GoVersion:"go1.24.2"}
```

### Additional Information

Same behavior happens when `global.workspaceMode` is set to `SAAS`.

The error does not seem to break any application functionality, but it clutters the logs since it is almost 500 lines long.
