### ISSUE TITLE
[Feat]: Documentation on deploying selfhost with Traefik

### ISSUE THREAD

**Issue by timconsidine** [lowcoder-org/lowcoder#502]
**Is your feature request related to a problem? Please describe.**
I followed the docs for selfhost deployment of all-in-one instance on a VPS which has Traefik to manage reverse proxy and SSL.
Deployed fine but encountered `Bad Gateway`.
After much investigation, I discovered that an additional Traefik label was needed.

`- "traefik.http.services.lowcoder.loadbalancer.server.port=3000"`

**Describe the solution you'd like**
Documentation in selfhost section for Traefik deployment.
Would save people a lot of time.

**Additional context**
These are my additional lines for the docker-compose.yaml file
Removed the `ports` lines earlier in the docker-compose.yaml file.
```
    labels:
      - traefik.docker.network=traefik
      - traefik.port=3000
      - traefik.port=3443
      - "traefik.enable=true"
      - "traefik.http.routers.lowcoder.rule=Host(`lowcoder.domain.tld`)"
      - "traefik.http.routers.lowcoder.entrypoints=websecure"
      - "traefik.http.routers.lowcoder.tls.certresolver=letsencrypt"
      - "traefik.http.services.lowcoder.loadbalancer.server.port=3000"
    networks:
      - traefik

networks:
  traefik:
    external: true
```

**Comment by FalkWolsky** [comment]
That is a truly valuable contribution! We will put this in the documentation.
Could I ask you to send the whole docker-compose.yaml - so we can compare and take over your changes?

**Comment by timconsidine** [comment]
Sure, here is my docker-compose.yaml with Traefik support.
Of course, it's just my config, but it's pretty standard config for Traefik.
`ports` in your version has been moved to Traefik section.
Comments in your version (very helpful) removed for deployment. 
```
version: "3"

services:
  ## Start Lowcoder (all-in-one)
  lowcoder-api-service:
    image: lowcoderorg/lowcoder-ce:latest
    container_name: lowcoder
    environment:
      REDIS_ENABLED: "true"
      MONGODB_ENABLED: "true"
      API_SERVICE_ENABLED: "true"
      NODE_SERVICE_ENABLED: "true"
      FRONTEND_ENABLED: "true"
      PUID: "1000"
      PGID: "1000"
      DEFAULT_ORGS_PER_USER: 100
      DEFAULT_ORG_MEMBER_COUNT: 1000
      DEFAULT_ORG_GROUP_COUNT: 100
      DEFAULT_ORG_APP_COUNT: 1000
      DEFAULT_DEVELOPER_COUNT: 50
      MONGODB_URL: "mongodb://localhost:27017/lowcoder?authSource=admin"
      REDIS_URL: "redis://localhost:6379"
      ENABLE_USER_SIGN_UP: "false"
      ENCRYPTION_PASSWORD: "somethingveryunique"
      ENCRYPTION_SALT: "somethingalsounique"
      CORS_ALLOWED_DOMAINS: "*"
      LOWCODER_API_KEY_SECRET: "b37717ee6de1003921c4445a3088af17ee316a6fad270737282a8ce2acf29832"
      LOWCODER_API_SERVICE_URL: "http://localhost:8080"
      LOWCODER_NODE_SERVICE_URL: "http://localhost:6060"
      LOWCODER_MAX_REQUEST_SIZE: 20m
      LOWCODER_MAX_QUERY_TIMEOUT: 120
    volumes:
      - ./lowcoder-stacks:/lowcoder-stacks
    restart: unless-stopped
    labels:
      - traefik.docker.network=traefik
      - traefik.port=3000
      - traefik.port=3443
      - "traefik.enable=true"
      - "traefik.http.routers.lowcoder.rule=Host(`lowcoder.domain.tld`)"
      - "traefik.http.routers.lowcoder.entrypoints=websecure"
      - "traefik.http.routers.lowcoder.tls.certresolver=letsencrypt"
      - "traefik.http.services.lowcoder.loadbalancer.server.port=3000"
    networks:
      - traefik

networks:
  traefik:
    external: true
```
Hope this helps.
